// This file was automatically generated by make-pins.py
//
// --board-csv /Users/kevinsanto/Documents/GitHub/Temporal-Replay-26-Badge/firmware/micropython/embed_config/temporal_badge_pins.csv
// --prefix /Users/kevinsanto/Documents/GitHub/Temporal-Replay-26-Badge/firmware/micropython/micropython_repo/ports/esp32/boards/pins_prefix.c

#include "py/obj.h"
#include "extmod/modmachine.h"
#include "machine_pin.h"
#include "genhdr/pins.h"

const machine_pin_obj_t machine_pin_obj_table[GPIO_NUM_MAX] = {
    #if MICROPY_HW_ENABLE_GPIO0
    [GPIO_NUM_0] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO1
    [GPIO_NUM_1] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO2
    [GPIO_NUM_2] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO3
    [GPIO_NUM_3] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO4
    [GPIO_NUM_4] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO5
    [GPIO_NUM_5] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO6
    [GPIO_NUM_6] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO7
    [GPIO_NUM_7] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO8
    [GPIO_NUM_8] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO9
    [GPIO_NUM_9] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO10
    [GPIO_NUM_10] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO11
    [GPIO_NUM_11] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO12
    [GPIO_NUM_12] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO13
    [GPIO_NUM_13] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO14
    [GPIO_NUM_14] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO15
    [GPIO_NUM_15] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO16
    [GPIO_NUM_16] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO17
    [GPIO_NUM_17] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO18
    [GPIO_NUM_18] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO19
    [GPIO_NUM_19] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO20
    [GPIO_NUM_20] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO21
    [GPIO_NUM_21] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO22
    [GPIO_NUM_22] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO23
    [GPIO_NUM_23] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO24
    [GPIO_NUM_24] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO25
    [GPIO_NUM_25] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO26
    [GPIO_NUM_26] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO27
    [GPIO_NUM_27] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO28
    [GPIO_NUM_28] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO29
    [GPIO_NUM_29] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO30
    [GPIO_NUM_30] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO31
    [GPIO_NUM_31] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO32
    [GPIO_NUM_32] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO33
    [GPIO_NUM_33] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO34
    [GPIO_NUM_34] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO35
    [GPIO_NUM_35] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO36
    [GPIO_NUM_36] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO37
    [GPIO_NUM_37] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO38
    [GPIO_NUM_38] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO39
    [GPIO_NUM_39] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO40
    [GPIO_NUM_40] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO41
    [GPIO_NUM_41] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO42
    [GPIO_NUM_42] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO43
    [GPIO_NUM_43] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO44
    [GPIO_NUM_44] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO45
    [GPIO_NUM_45] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO46
    [GPIO_NUM_46] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO47
    [GPIO_NUM_47] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO48
    [GPIO_NUM_48] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO49
    [GPIO_NUM_49] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO50
    [GPIO_NUM_50] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO51
    [GPIO_NUM_51] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO52
    [GPIO_NUM_52] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO53
    [GPIO_NUM_53] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
    #if MICROPY_HW_ENABLE_GPIO54
    [GPIO_NUM_54] = { .base = { .type = &machine_pin_type }, .irq = { .base = { .type = &machine_pin_irq_type } } },
    #endif
};


static const mp_rom_map_elem_t machine_pin_board_pins_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_I2C_SDA), MP_ROM_PTR(pin_GPIO5) },
    { MP_ROM_QSTR(MP_QSTR_I2C_SCL), MP_ROM_PTR(pin_GPIO6) },
    { MP_ROM_QSTR(MP_QSTR_SPI_SS), MP_ROM_PTR(pin_GPIO15) },
    { MP_ROM_QSTR(MP_QSTR_SPI_MOSI), MP_ROM_PTR(pin_GPIO16) },
    { MP_ROM_QSTR(MP_QSTR_SPI_SCK), MP_ROM_PTR(pin_GPIO17) },
    { MP_ROM_QSTR(MP_QSTR_SPI_MISO), MP_ROM_PTR(pin_GPIO18) },
    { MP_ROM_QSTR(MP_QSTR_RGB_DATA), MP_ROM_PTR(pin_GPIO41) },
    { MP_ROM_QSTR(MP_QSTR_RGB_PWR), MP_ROM_PTR(pin_GPIO42) },
    { MP_ROM_QSTR(MP_QSTR_UART0_TX), MP_ROM_PTR(pin_GPIO43) },
    { MP_ROM_QSTR(MP_QSTR_UART0_RX), MP_ROM_PTR(pin_GPIO44) },
};
MP_DEFINE_CONST_DICT(machine_pin_board_pins_locals_dict, machine_pin_board_pins_locals_dict_table);
