#!/usr/bin/env python3
"""
badge_sync.py — Self-contained filesystem diff-sync for the Temporal Badge.

The badge ships with a tiny survival-floor in app0 (`/lib`, `/matrixApps`).
Everything else (`/apps`, `/docs`, `/images`, `/messages`, ...) lives on the
FATFS partition and is shipped one of three ways:

    1. Factory flash via Ignition: FATFS is written at the same time as the
       firmware. Already populates everything.
    2. `pio run -t uploadfs`: developer flow. Same image as #1.
    3. Community Apps (on-badge) / JumperIDE / **this script**: post-flash
       sync over USB serial. Picks up missing or stale files from the
       generator's manifest and pushes them via the MicroPython raw REPL.

When to use this script
-----------------------
- After a firmware-only reflash that didn't include `fatfs.bin`.
- To repair a badge whose FATFS got wedged / corrupted.
- In CI, automation, or a Temporal activity (`from badge_sync import sync`).

Storage model (mental model)
----------------------------
                ┌──────────────────────────────────────────────┐
                │ NVS                                          │
                │   badge UID, HMAC, WiFi creds, contacts,     │
                │   badgeInfo, badge.kv (saves/scores), asset  │
                │   versions, menu order — survives EVERY      │
                │   flash; this script never touches it.       │
                ├──────────────────────────────────────────────┤
                │ FATFS                                        │
                │   /lib, /matrixApps   (also baked in app0)   │
                │   /apps/*, /docs/*, /images/*, /messages/*   │
                │   user uploads — what THIS script syncs.     │
                ├──────────────────────────────────────────────┤
                │ app0 (firmware)                              │
                │   C++ + embedded /lib + /matrixApps —        │
                │   replaced only by a firmware flash.         │
                └──────────────────────────────────────────────┘

Wire protocol
-------------
Pure MicroPython raw REPL (Ctrl-A / Ctrl-D, the same protocol mpremote and
JumperIDE speak). We:

    1. Enter raw REPL
    2. Send a small Python script that walks `/`, hashes each file with
       FNV-1a, prints `f|<path>|<size>|0xXXXXXXXX` lines, ends with
       `OK|<count>`.
    3. Diff against firmware/data/manifest.json (generated by
       generate_startup_files.py).
    4. Push missing/stale files via raw-paste write of a small upload
       script, chunked by base64-encoded payloads to avoid embedding
       arbitrary bytes in REPL strings.

Public API
----------
    list_badge(port)          -> list[BadgeFile]
    load_manifest(data_dir)   -> dict[path -> ManifestFile]
    diff(badge, manifest)     -> SyncPlan
    push_files(port, paths, data_dir, progress_cb=None)
    clear_paths(port, paths)
    sync(port, data_dir, **opts) -> SyncResult

CLI
---
    python3 -m badge_sync sync /dev/cu.usbmodemXXX
    python3 -m badge_sync list /dev/cu.usbmodemXXX
    python3 -m badge_sync diff /dev/cu.usbmodemXXX            # dry-run
    python3 -m badge_sync push /dev/cu.usbmodemXXX /apps/a.py
    python3 -m badge_sync clear /dev/cu.usbmodemXXX /apps/a.py
"""

from __future__ import annotations

import argparse
import base64
import dataclasses
import json
import os
import sys
import time
from pathlib import Path
from typing import Callable, Iterable, Optional

try:
    import serial
except ImportError:
    serial = None  # CLI only; library users may import without pyserial.


# ── Protocol constants ──────────────────────────────────────────────────────

CTRL_A = b"\x01"  # raw REPL on
CTRL_B = b"\x02"  # friendly REPL on
CTRL_C = b"\x03"  # interrupt
CTRL_D = b"\x04"  # raw REPL submit / soft reboot

DEFAULT_BAUD = 115200
DEFAULT_TIMEOUT = 5.0

# Server-side script: list every regular file under /, FNV-1a hash, size,
# print as `f|<path>|<size>|0xXXXXXXXX`. Skips dotfiles and tmp files
# (these are write-in-progress artefacts the badge never wants synced).
LIST_SCRIPT = r"""
import os
def _fnv(p):
 h=0x811C9DC5
 try:
  with open(p,'rb') as f:
   while True:
    b=f.read(256)
    if not b: break
    for x in b:
     h^=x; h=(h*0x01000193)&0xFFFFFFFF
 except: return None
 return h
def _walk(d):
 try: it=os.ilistdir(d)
 except OSError: return
 for n,t,_,*sz in it:
  if n.startswith('.') or n.endswith('.tmp'): continue
  fp=d.rstrip('/')+'/'+n if d!='/' else '/'+n
  if t&0x4000:
   _walk(fp)
  else:
   sb=sz[0] if sz else 0
   try: sb=os.stat(fp)[6]
   except: pass
   h=_fnv(fp)
   if h is not None: print('f|%s|%d|0x%08X'%(fp,sb,h))
_walk('/')
print('OK|done')
"""


# ── Data classes ────────────────────────────────────────────────────────────

@dataclasses.dataclass
class BadgeFile:
    """A file as the badge currently sees it on FATFS."""
    path: str
    size: int
    fnv1a32: int


@dataclasses.dataclass
class ManifestFile:
    """A file as the manifest (firmware/data/manifest.json) describes it."""
    path: str
    size: int
    fnv1a32: int
    sha256: str
    baked: bool


@dataclasses.dataclass
class SyncPlan:
    """Result of diff(): four buckets, all keyed by absolute path."""
    missing: list[ManifestFile]   # in manifest, not on badge
    stale: list[ManifestFile]     # on badge but hash differs
    unchanged: list[ManifestFile] # on badge, hash matches
    extras: list[BadgeFile]       # on badge, not in manifest

    def is_clean(self) -> bool:
        return not (self.missing or self.stale)


@dataclasses.dataclass
class SyncResult:
    plan: SyncPlan
    pushed: list[str]
    cleared: list[str]
    skipped: list[str]
    errors: list[str]

    @property
    def ok(self) -> bool:
        return not self.errors


# ── Raw REPL transport ──────────────────────────────────────────────────────

class RawRepl:
    """Minimal mpremote-compatible raw REPL client.

    Wraps a pyserial connection and exposes:
        enter() / exit()       — toggle raw REPL mode
        exec_(script)          — send a script, return stdout (bytes)
        exec_streaming(script, line_cb)
                               — same but streams stdout line-by-line so we
                                  can parse `f|...` listings without buffering
                                  the entire badge tree in memory."""

    def __init__(self, port: str, baud: int = DEFAULT_BAUD,
                 timeout: float = DEFAULT_TIMEOUT):
        if serial is None:
            raise RuntimeError(
                "pyserial is required: pip install pyserial")
        self.ser = serial.Serial(port, baud, timeout=timeout)
        self.timeout = timeout

    def close(self) -> None:
        try:
            self.ser.close()
        except Exception:
            pass

    def __enter__(self):
        self.enter()
        return self

    def __exit__(self, *exc):
        try:
            self.exit()
        finally:
            self.close()

    # ── low-level helpers ──────────────────────────────────────────────

    def _read_until(self, terminator: bytes, deadline: float) -> bytes:
        buf = b""
        while not buf.endswith(terminator):
            if time.monotonic() > deadline:
                raise TimeoutError(
                    f"timed out waiting for {terminator!r}; got {buf[-80:]!r}")
            chunk = self.ser.read(1) or b""
            if not chunk:
                continue
            buf += chunk
        return buf

    def _flush(self) -> None:
        try:
            self.ser.reset_input_buffer()
        except Exception:
            pass

    # ── raw REPL state machine ─────────────────────────────────────────

    def enter(self) -> None:
        """Drop into raw REPL. Idempotent."""
        # Three Ctrl-Cs interrupt any running program. Then Ctrl-B to
        # ensure friendly mode (so the next \r prints a known prompt),
        # then Ctrl-A to enter raw.
        self.ser.write(CTRL_C * 3)
        time.sleep(0.05)
        self._flush()
        self.ser.write(b"\r" + CTRL_B)
        time.sleep(0.05)
        self._flush()
        # Try to enter raw REPL with a few retries — early in boot the
        # firmware-side REPL prints banner garbage that can interleave.
        deadline = time.monotonic() + 3.0
        last_err = None
        while time.monotonic() < deadline:
            self.ser.write(b"\r" + CTRL_A)
            try:
                self._read_until(b"raw REPL; CTRL-B to exit\r\n>", deadline)
                return
            except TimeoutError as e:
                last_err = e
                self.ser.write(CTRL_C * 2)
                time.sleep(0.1)
                self._flush()
        raise RuntimeError(
            f"could not enter raw REPL on {self.ser.port}: {last_err}")

    def exit(self) -> None:
        try:
            self.ser.write(b"\r" + CTRL_B)
            time.sleep(0.05)
            self._flush()
        except Exception:
            pass

    def exec_(self, script: str, timeout: Optional[float] = None) -> bytes:
        """Submit `script` over raw REPL, return collected stdout bytes."""
        out = bytearray()

        def collect(line: bytes) -> None:
            out.extend(line)
            out.extend(b"\n")

        self.exec_streaming(script, collect, timeout=timeout)
        return bytes(out)

    def exec_streaming(self, script: str, line_cb: Callable[[bytes], None],
                       timeout: Optional[float] = None) -> None:
        """Submit `script` over raw REPL, calling `line_cb(line)` for each
        complete stdout line (without trailing \\n).

        Trailing partial line (no newline) is still delivered if non-empty.
        Raises RuntimeError on a Python exception coming back over the
        stderr channel."""
        if timeout is None:
            timeout = max(self.timeout, 30.0)
        deadline = time.monotonic() + timeout

        # Submit body. Raw REPL framing: <body>\x04, expect 'OK' echo,
        # then the body's stdout, then \x04, then stderr, then \x04>.
        self.ser.write(script.encode("utf-8"))
        self.ser.write(CTRL_D)
        # Confirmation — varies between MP versions ('OK' or empty).
        self._read_until(b"OK", deadline)

        # Stream stdout up to the first \x04.
        buf = bytearray()
        while True:
            if time.monotonic() > deadline:
                raise TimeoutError("script execution timed out")
            chunk = self.ser.read(256) or b""
            if not chunk:
                continue
            for byte in chunk:
                if byte == 0x04:
                    if buf:
                        line_cb(bytes(buf))
                        buf.clear()
                    # fall through to read stderr
                    err = self._read_until(b"\x04", deadline)
                    err = err.rstrip(b"\x04")
                    # The closing prompt is sometimes consumed already;
                    # try to swallow a trailing '>' but don't insist.
                    try:
                        self.ser.read(1)
                    except Exception:
                        pass
                    if err.strip():
                        raise RuntimeError(
                            f"badge raised:\n{err.decode('utf-8', 'replace')}")
                    return
                if byte == 0x0a:
                    line_cb(bytes(buf))
                    buf.clear()
                else:
                    buf.append(byte)


# ── Public API ──────────────────────────────────────────────────────────────

def load_manifest(data_dir: Path) -> dict[str, ManifestFile]:
    """Load firmware/data/manifest.json into a {path: ManifestFile} dict."""
    mp = data_dir / "manifest.json"
    if not mp.exists():
        raise FileNotFoundError(
            f"{mp} missing — run scripts/generate_startup_files.py first.")
    blob = json.loads(mp.read_text())
    out: dict[str, ManifestFile] = {}
    for f in blob.get("files", []):
        path = f["path"]
        out[path] = ManifestFile(
            path=path,
            size=int(f["size"]),
            fnv1a32=int(f["fnv1a32"], 16) if isinstance(f["fnv1a32"], str)
                                          else int(f["fnv1a32"]),
            sha256=f.get("sha256", ""),
            baked=bool(f.get("baked", False)),
        )
    return out


def list_badge(port: str, baud: int = DEFAULT_BAUD,
               timeout: float = DEFAULT_TIMEOUT) -> list[BadgeFile]:
    """Connect, list FATFS, disconnect. Convenience wrapper."""
    with RawRepl(port, baud, timeout) as repl:
        return _list_via(repl)


def _list_via(repl: RawRepl) -> list[BadgeFile]:
    files: list[BadgeFile] = []

    def on_line(line: bytes) -> None:
        text = line.decode("utf-8", "replace").strip()
        if not text:
            return
        if text.startswith("f|"):
            try:
                _, path, size, hexh = text.split("|", 3)
                files.append(BadgeFile(
                    path=path,
                    size=int(size),
                    fnv1a32=int(hexh, 16),
                ))
            except (ValueError, IndexError):
                pass
        # 'OK|done' marks completion, ignore other lines silently.

    repl.exec_streaming(LIST_SCRIPT, on_line, timeout=120.0)
    return files


def diff(badge: list[BadgeFile],
         manifest: dict[str, ManifestFile]) -> SyncPlan:
    badge_by_path = {f.path: f for f in badge}
    missing: list[ManifestFile] = []
    stale: list[ManifestFile] = []
    unchanged: list[ManifestFile] = []
    for path, m in manifest.items():
        b = badge_by_path.get(path)
        if b is None:
            missing.append(m)
        elif b.fnv1a32 != m.fnv1a32 or b.size != m.size:
            stale.append(m)
        else:
            unchanged.append(m)
    extras = [f for p, f in badge_by_path.items() if p not in manifest]
    return SyncPlan(missing=missing, stale=stale,
                    unchanged=unchanged, extras=extras)


# ── Push / clear ────────────────────────────────────────────────────────────

# Server-side write helper. Receives base64 chunks via input(); the
# caller streams "<chunk>\n" for each piece, terminated by an empty line.
# We ensureDir parents before writing and write atomically by writing to
# `<path>.tmp` then `os.rename()`. Limits: we cap path length to 96 chars
# and reject paths that don't start with '/' for safety.
WRITE_PROLOGUE = r"""
import os, ubinascii
def _ensure(p):
 if p in ('','/'): return
 try: os.stat(p)
 except OSError:
  _ensure(p.rsplit('/',1)[0] or '/')
  try: os.mkdir(p)
  except OSError: pass
def _put(p):
 if not p.startswith('/') or len(p)>96:
  raise ValueError('bad path')
 d=p.rsplit('/',1)[0] or '/'
 _ensure(d)
 tmp=p+'.tmp'
 try: os.remove(tmp)
 except OSError: pass
 with open(tmp,'wb') as f:
  while True:
   line=input()
   if not line: break
   f.write(ubinascii.a2b_base64(line))
 try: os.remove(p)
 except OSError: pass
 os.rename(tmp,p)
print('PUT_READY')
"""

CLEAR_SCRIPT = r"""
import os
def _rm(p):
 try: os.remove(p); print('rm '+p)
 except OSError as e: print('skip '+p+' ('+str(e)+')')
for _p in {paths!r}:
 _rm(_p)
print('OK|cleared')
"""


def push_files(port: str, paths: Iterable[str], data_dir: Path,
               progress_cb: Optional[Callable[[str, int, int], None]] = None,
               baud: int = DEFAULT_BAUD,
               timeout: float = DEFAULT_TIMEOUT) -> None:
    """Upload `paths` (each a manifest path like '/apps/foo.py') from
    `data_dir` to the badge's FATFS at the same path.

    `progress_cb(path, bytes_pushed, total_bytes)` fires once per file."""
    paths = list(paths)
    if not paths:
        return
    with RawRepl(port, baud, timeout) as repl:
        # We use a different strategy than the LIST script: instead of
        # one big script, we send the prologue once (which leaves a
        # function `_put` defined), then for each file we exec a small
        # script that calls `_put('/path')` and streams base64 chunks
        # via input(). This keeps memory bounded on the badge.
        for path in paths:
            local = data_dir / path.lstrip("/")
            if not local.is_file():
                raise FileNotFoundError(f"manifest path not on disk: {local}")
            data = local.read_bytes()
            # 192-byte raw chunks -> 256-char base64 lines, stays under
            # MicroPython's input() line buffer comfortably.
            chunks = [
                base64.b64encode(data[i:i + 192]).decode("ascii")
                for i in range(0, len(data), 192)
            ]
            script = WRITE_PROLOGUE + f"_put({path!r})\n"
            for c in chunks:
                script += c + "\n"
            script += "\n"  # empty line terminates the inner loop
            script += "print('OK|wrote',%r,len(open(%r,'rb').read()))\n" % (
                path, path)
            repl.exec_(script, timeout=max(timeout, 60.0))
            if progress_cb:
                progress_cb(path, len(data), len(data))


def clear_paths(port: str, paths: Iterable[str],
                baud: int = DEFAULT_BAUD,
                timeout: float = DEFAULT_TIMEOUT) -> None:
    paths = list(paths)
    if not paths:
        return
    script = CLEAR_SCRIPT.format(paths=paths)
    with RawRepl(port, baud, timeout) as repl:
        repl.exec_(script, timeout=max(timeout, 30.0))


# ── High-level sync ─────────────────────────────────────────────────────────

def sync(port: str, data_dir: Path, *,
         push_missing: bool = True,
         push_stale: bool = True,
         clear_extras: bool = False,
         clear_stale: bool = False,
         progress_cb: Optional[Callable[[str, int, int], None]] = None,
         baud: int = DEFAULT_BAUD,
         timeout: float = DEFAULT_TIMEOUT) -> SyncResult:
    """End-to-end: connect → list → diff → push/clear → return result."""
    manifest = load_manifest(data_dir)
    pushed: list[str] = []
    cleared: list[str] = []
    skipped: list[str] = []
    errors: list[str] = []

    with RawRepl(port, baud, timeout) as repl:
        try:
            badge = _list_via(repl)
        except Exception as e:
            return SyncResult(
                plan=SyncPlan([], [], [], []),
                pushed=[], cleared=[], skipped=[], errors=[f"list failed: {e}"])
        plan = diff(badge, manifest)

        to_push: list[str] = []
        if push_missing:
            to_push.extend(m.path for m in plan.missing)
        else:
            skipped.extend(m.path for m in plan.missing)
        if push_stale:
            to_push.extend(m.path for m in plan.stale)
        elif not clear_stale:
            skipped.extend(m.path for m in plan.stale)

        for p in to_push:
            local = data_dir / p.lstrip("/")
            if not local.is_file():
                errors.append(f"manifest path not on disk: {p}")
                continue
            data = local.read_bytes()
            try:
                chunks = [
                    base64.b64encode(data[i:i + 192]).decode("ascii")
                    for i in range(0, len(data), 192)
                ]
                script = WRITE_PROLOGUE + f"_put({p!r})\n"
                for c in chunks:
                    script += c + "\n"
                script += "\n"
                script += "print('OK')\n"
                repl.exec_(script, timeout=max(timeout, 60.0))
                pushed.append(p)
                if progress_cb:
                    progress_cb(p, len(data), len(data))
            except Exception as e:
                errors.append(f"push {p}: {e}")

        to_clear: list[str] = []
        if clear_extras:
            to_clear.extend(b.path for b in plan.extras)
        if clear_stale:
            to_clear.extend(m.path for m in plan.stale)
        if to_clear:
            try:
                script = CLEAR_SCRIPT.format(paths=to_clear)
                repl.exec_(script, timeout=max(timeout, 30.0))
                cleared.extend(to_clear)
            except Exception as e:
                errors.append(f"clear: {e}")

    return SyncResult(plan=plan, pushed=pushed, cleared=cleared,
                      skipped=skipped, errors=errors)


# ── CLI ────────────────────────────────────────────────────────────────────

def _cmd_list(args) -> int:
    files = list_badge(args.port, args.baud, args.timeout)
    for f in files:
        print(f"{f.path}\t{f.size}\t0x{f.fnv1a32:08X}")
    print(f"# {len(files)} files")
    return 0


def _cmd_diff(args) -> int:
    data_dir = Path(args.data_dir).resolve()
    manifest = load_manifest(data_dir)
    badge = list_badge(args.port, args.baud, args.timeout)
    plan = diff(badge, manifest)
    print(f"Manifest: {len(manifest)} files")
    print(f"Badge:    {len(badge)} files")
    print(f"  missing:   {len(plan.missing)}")
    print(f"  stale:     {len(plan.stale)}")
    print(f"  unchanged: {len(plan.unchanged)}")
    print(f"  extras:    {len(plan.extras)}")
    if args.verbose:
        for m in plan.missing:
            print(f"  - missing {m.path}")
        for m in plan.stale:
            print(f"  ~ stale   {m.path}")
        for b in plan.extras:
            print(f"  + extra   {b.path}")
    return 0 if plan.is_clean() else 1


def _cmd_sync(args) -> int:
    data_dir = Path(args.data_dir).resolve()

    def progress(path: str, n: int, total: int) -> None:
        print(f"  pushed {path}  ({n} B)")

    res = sync(
        args.port, data_dir,
        push_missing=not args.no_push_missing,
        push_stale=not args.no_push_stale,
        clear_extras=args.clear_extras,
        clear_stale=args.clear_stale,
        progress_cb=progress if args.verbose else None,
        baud=args.baud,
        timeout=args.timeout,
    )
    print(f"Sync: pushed={len(res.pushed)} cleared={len(res.cleared)} "
          f"skipped={len(res.skipped)} errors={len(res.errors)}")
    for e in res.errors:
        print(f"  ! {e}", file=sys.stderr)
    return 0 if res.ok else 1


def _cmd_push(args) -> int:
    data_dir = Path(args.data_dir).resolve()
    push_files(args.port, args.path, data_dir,
               baud=args.baud, timeout=args.timeout)
    print(f"Pushed {len(args.path)} file(s).")
    return 0


def _cmd_clear(args) -> int:
    clear_paths(args.port, args.path,
                baud=args.baud, timeout=args.timeout)
    print(f"Cleared {len(args.path)} file(s).")
    return 0


def _default_data_dir() -> Path:
    here = Path(__file__).resolve().parent
    # firmware/scripts/badge_sync.py → firmware/data
    return here.parent / "data"


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="badge_sync",
        description="Diff-sync the badge filesystem against firmware/data/.")
    p.add_argument("--data-dir", default=str(_default_data_dir()),
                   help="Source-of-truth directory (default: firmware/data/).")
    p.add_argument("--baud", type=int, default=DEFAULT_BAUD)
    p.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)

    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("list", help="List files on the badge.")
    sp.add_argument("port")
    sp.set_defaults(func=_cmd_list)

    sp = sub.add_parser("diff", help="Show what would change (dry run).")
    sp.add_argument("port")
    sp.add_argument("-v", "--verbose", action="store_true")
    sp.set_defaults(func=_cmd_diff)

    sp = sub.add_parser("sync", help="Push missing+stale; optional clear.")
    sp.add_argument("port")
    sp.add_argument("-v", "--verbose", action="store_true")
    sp.add_argument("--no-push-missing", action="store_true")
    sp.add_argument("--no-push-stale", action="store_true")
    sp.add_argument("--clear-extras", action="store_true",
                    help="Delete files on the badge not in the manifest.")
    sp.add_argument("--clear-stale", action="store_true",
                    help="Delete stale files (instead of overwriting).")
    sp.set_defaults(func=_cmd_sync)

    sp = sub.add_parser("push", help="Upload one or more manifest paths.")
    sp.add_argument("port")
    sp.add_argument("path", nargs="+")
    sp.set_defaults(func=_cmd_push)

    sp = sub.add_parser("clear", help="Remove one or more files.")
    sp.add_argument("port")
    sp.add_argument("path", nargs="+")
    sp.set_defaults(func=_cmd_clear)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
