#!/usr/bin/env python3
"""
Generate src/infra/BuildWifiConfig.generated.h from local build inputs.

Set credentials per build with environment variables:
  BADGE_WIFI_SSID
  BADGE_WIFI_PASS

Or create firmware/wifi.local.env, which is ignored by git:
  BADGE_WIFI_SSID=YourNetwork
  BADGE_WIFI_PASS=YourPassword

Both values are optional. The generated header stores only lightly obfuscated
bytes. This keeps secrets out of settings.txt, NVS, and casual `strings`
output, but it is not cryptographic protection against a motivated firmware
reverse engineer.
"""

from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path

try:
    Import("env")  # type: ignore[name-defined]
except NameError:
    env = None


SSID_SALT = 0xA71C3D5B
PASS_SALT = 0xC8E52F91
SERVER_SALT = 0x6B4F8E27
GOLDEN = 0x9E3779B9


def project_dir() -> Path:
    if env is not None:
        return Path(env.subst("$PROJECT_DIR"))
    return Path(__file__).resolve().parents[1]


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        values[key] = value
    return values


def env_value(local: dict[str, str], *names: str) -> str:
    for name in names:
        value = os.environ.get(name)
        if value is not None:
            return value
    for name in names:
        if name in local:
            return local[name]
    return ""


def key_byte(seed: int, salt: int, index: int) -> int:
    x = (seed ^ salt ^ (((index + 1) * GOLDEN) & 0xFFFFFFFF)) & 0xFFFFFFFF
    x ^= x >> 16
    x = (x * 0x7FEB352D) & 0xFFFFFFFF
    x ^= x >> 15
    x = (x * 0x846CA68B) & 0xFFFFFFFF
    x ^= x >> 16
    return x & 0xFF


def encode(data: bytes, seed: int, salt: int) -> list[int]:
    return [b ^ key_byte(seed, salt, i) for i, b in enumerate(data)]


def c_array(values: list[int]) -> str:
    if not values:
        return "0x00"
    return ", ".join(f"0x{value:02X}" for value in values)


def validate(ssid: str, password: str) -> None:
    ssid_bytes = ssid.encode("utf-8")
    pass_bytes = password.encode("utf-8")

    if len(ssid_bytes) > 32:
        raise ValueError("BADGE_WIFI_SSID must be 32 bytes or fewer")
    if bool(ssid) != bool(password):
        raise ValueError("BADGE_WIFI_SSID and BADGE_WIFI_PASS must be set together")
    if pass_bytes and (len(pass_bytes) < 8 or len(pass_bytes) > 64):
        raise ValueError("BADGE_WIFI_PASS must be 8..64 bytes")
    if re.search(r"[\r\n\x00]", ssid + password):
        raise ValueError("BADGE_WIFI_SSID/PASS must not contain control newlines or NUL")


def render_header(ssid: str, password: str) -> str:
    ssid_bytes = ssid.encode("utf-8")
    pass_bytes = password.encode("utf-8")
    seed_bytes = hashlib.sha256(
        b"replay-26-build-network\0" + ssid_bytes + b"\0" +
        pass_bytes
    ).digest()
    seed = int.from_bytes(seed_bytes[:4], "little") or 0x6D2B79F5

    ssid_data = encode(ssid_bytes, seed, SSID_SALT)
    pass_data = encode(pass_bytes, seed, PASS_SALT)
    ssid_array_len = max(1, len(ssid_data))
    pass_array_len = max(1, len(pass_data))

    return f"""#pragma once
// Generated by scripts/generate_build_wifi_config.py. Do not commit.
// Stores obfuscated build-time network config; this is not cryptographic.

#include <stddef.h>
#include <stdint.h>

namespace BuildWifiConfig {{
static constexpr size_t kSsidLen = {len(ssid_data)}u;
static constexpr size_t kPassLen = {len(pass_data)}u;
static constexpr uint32_t kSeed = 0x{seed:08X}u;
static constexpr uint32_t kSsidSalt = 0x{SSID_SALT:08X}u;
static constexpr uint32_t kPassSalt = 0x{PASS_SALT:08X}u;

static const uint8_t kSsidData[{ssid_array_len}] = {{ {c_array(ssid_data)} }};
static const uint8_t kPassData[{pass_array_len}] = {{ {c_array(pass_data)} }};

#if defined(__GNUC__)
#define BADGE_WIFI_NOINLINE __attribute__((noinline))
#else
#define BADGE_WIFI_NOINLINE
#endif

static BADGE_WIFI_NOINLINE uint8_t keyByte(size_t index, uint32_t salt) {{
  uint32_t x = kSeed ^ salt ^
               (static_cast<uint32_t>(index + 1u) * 0x9E3779B9u);
  volatile uint32_t barrier = x;
  x = barrier;
  x ^= x >> 16;
  x *= 0x7FEB352Du;
  x ^= x >> 15;
  x *= 0x846CA68Bu;
  x ^= x >> 16;
  return static_cast<uint8_t>(x & 0xFFu);
}}

static BADGE_WIFI_NOINLINE void decodeBytes(const uint8_t* data, size_t len,
                                            char* out, size_t cap,
                                            uint32_t salt) {{
  if (out == nullptr || cap == 0) return;
  const size_t n = (len < cap - 1u) ? len : cap - 1u;
  for (size_t i = 0; i < n; ++i) {{
    out[i] = static_cast<char>(data[i] ^ keyByte(i, salt));
  }}
  out[n] = '\\0';
}}

inline bool hasWifi() {{
  return kSsidLen > 0 && kPassLen > 0;
}}

inline void decodeSsid(char* out, size_t cap) {{
  decodeBytes(kSsidData, kSsidLen, out, cap, kSsidSalt);
}}

inline void decodePass(char* out, size_t cap) {{
  decodeBytes(kPassData, kPassLen, out, cap, kPassSalt);
}}

#undef BADGE_WIFI_NOINLINE
}}  // namespace BuildWifiConfig
"""


def main() -> None:
    root = project_dir()
    local = parse_env_file(root / "wifi.local.env")
    ssid = env_value(local, "BADGE_WIFI_SSID")
    password = env_value(local, "BADGE_WIFI_PASS", "BADGE_WIFI_PASSWORD")
    output = root / "src" / "infra" / "BuildWifiConfig.generated.h"

    try:
        validate(ssid, password)
    except ValueError as exc:
        print(f"[build_wifi_config] ERROR: {exc}")
        if env is not None:
            env.Exit(1)
        raise SystemExit(1)

    header = render_header(ssid, password)
    if not output.exists() or output.read_text(encoding="utf-8") != header:
        output.write_text(header, encoding="utf-8")

    if ssid and password:
        print(f"[build_wifi_config] Embedded build WiFi credentials (ssid_len={len(ssid.encode('utf-8'))})")
    else:
        print("[build_wifi_config] No build WiFi credentials set")

main()
