// QSTR declarations for modules whose port-level include files pull in
// FreeRTOS or other IDF headers that the host-side QSTR preprocessor
// cannot resolve. The QSTR scanner (`makeqstrdata.py`) extracts tokens
// from `MP_QSTR_xxx` identifiers found in `gcc -E` output — we place
// them in a void pointer array so they survive preprocessing.
//
// Keep in sync with extmod/machine_wdt.c + ports/esp32/machine_wdt.c.

#include "py/mpconfig.h"

#if !defined(NO_QSTR)
// Firmware build — nothing needed, the real .c files compile fine.
#else
// Host-side QSTR extraction pass.  Emit MP_QSTR_xxx tokens so they
// appear in the preprocessor output for makeqstrdata.py to collect.

void *replay_phase1_qstr_refs[] = {
    // machine.WDT
    (void *)MP_QSTR_WDT,
    (void *)MP_QSTR_feed,
    (void *)MP_QSTR_timeout_ms,
    // select module
    (void *)MP_QSTR_select,
    (void *)MP_QSTR_poll,
    (void *)MP_QSTR_POLLIN,
    (void *)MP_QSTR_POLLOUT,
    (void *)MP_QSTR_POLLERR,
    (void *)MP_QSTR_POLLHUP,
    (void *)MP_QSTR_ipoll,
    (void *)MP_QSTR_register,
    (void *)MP_QSTR_unregister,
    (void *)MP_QSTR_modify,
    // machine.Pulse (extmod/machine_pulse.c)
    (void *)MP_QSTR_time_pulse_us,
    // _thread module (py/modthread.c QSTRs hidden by REPLAY_ENABLE_THREAD=0 host pass)
    (void *)MP_QSTR__thread,
    (void *)MP_QSTR_start_new_thread,
    (void *)MP_QSTR_get_ident,
    (void *)MP_QSTR_exit,
    (void *)MP_QSTR_allocate_lock,
    (void *)MP_QSTR_Lock,
    (void *)MP_QSTR_lock,
    (void *)MP_QSTR_LockType,
    (void *)MP_QSTR_acquire,
    (void *)MP_QSTR_release,
    (void *)MP_QSTR_locked,
    (void *)MP_QSTR_stack_size,
    // sys module thread-gated entries
    (void *)MP_QSTR_GIL,
    // espnow module (ports/esp32/modespnow.c)
    (void *)MP_QSTR__espnow,
    (void *)MP_QSTR_ESPNowBase,
    (void *)MP_QSTR_active,
    (void *)MP_QSTR_config,
    (void *)MP_QSTR_irq,
    (void *)MP_QSTR_stats,
    (void *)MP_QSTR_recvinto,
    (void *)MP_QSTR_send,
    (void *)MP_QSTR_any,
    (void *)MP_QSTR_set_pmk,
    (void *)MP_QSTR_add_peer,
    (void *)MP_QSTR_del_peer,
    (void *)MP_QSTR_get_peers,
    (void *)MP_QSTR_mod_peer,
    (void *)MP_QSTR_get_peer,
    (void *)MP_QSTR_peer_count,
    (void *)MP_QSTR_peers_table,
    (void *)MP_QSTR_rxbuf,
    (void *)MP_QSTR_lmk,
    (void *)MP_QSTR_channel,
    (void *)MP_QSTR_ifidx,
    (void *)MP_QSTR_encrypt,
    (void *)MP_QSTR_MAX_DATA_LEN,
    (void *)MP_QSTR_ADDR_LEN,
    (void *)MP_QSTR_KEY_LEN,
    (void *)MP_QSTR_MAX_TOTAL_PEER_NUM,
    (void *)MP_QSTR_MAX_ENCRYPT_PEER_NUM,
    (void *)MP_QSTR_RATE_LORA_250K,
    (void *)MP_QSTR_RATE_LORA_500K,
    (void *)MP_QSTR_RATE_1M,
    (void *)MP_QSTR_RATE_2M,
    (void *)MP_QSTR_RATE_5M,
    (void *)MP_QSTR_RATE_6M,
    (void *)MP_QSTR_RATE_11M,
    (void *)MP_QSTR_RATE_12M,
    (void *)MP_QSTR_RATE_24M,
    (void *)MP_QSTR_RATE_54M,
    (void *)MP_QSTR_rate,
    // network_common.c
    (void *)MP_QSTR_dns,
    (void *)MP_QSTR_dhcp4,
    (void *)MP_QSTR_addr4,
    (void *)MP_QSTR_gw4,
    (void *)MP_QSTR_ipconfig,
    // network module globals (extmod/modnetwork.c)
    (void *)MP_QSTR_network,
    (void *)MP_QSTR_route,
    (void *)MP_QSTR_country,
    // network.WLAN (ports/esp32/network_wlan.c)
    (void *)MP_QSTR_WLAN,
    (void *)MP_QSTR_STA_IF,
    (void *)MP_QSTR_AP_IF,
    (void *)MP_QSTR_IF_STA,
    (void *)MP_QSTR_IF_AP,
    (void *)MP_QSTR_connect,
    (void *)MP_QSTR_disconnect,
    (void *)MP_QSTR_isconnected,
    (void *)MP_QSTR_scan,
    (void *)MP_QSTR_status,
    (void *)MP_QSTR_rssi,
    (void *)MP_QSTR_ifconfig,
    (void *)MP_QSTR_ifname,
    (void *)MP_QSTR_hostname,
    (void *)MP_QSTR_dhcp_hostname,
    (void *)MP_QSTR_phy_mode,
    (void *)MP_QSTR_essid,
    (void *)MP_QSTR_hidden,
    (void *)MP_QSTR_security,
    (void *)MP_QSTR_key,
    (void *)MP_QSTR_bssid,
    (void *)MP_QSTR_mac,
    (void *)MP_QSTR_authmode,
    (void *)MP_QSTR_txpower,
    (void *)MP_QSTR_protocol,
    (void *)MP_QSTR_pm,
    (void *)MP_QSTR_max_clients,
    (void *)MP_QSTR_reconnects,
    (void *)MP_QSTR_ssid,
    (void *)MP_QSTR_password,
    (void *)MP_QSTR_stations,
    (void *)MP_QSTR_SEC_OPEN,
    (void *)MP_QSTR_SEC_WEP,
    (void *)MP_QSTR_SEC_WPA,
    (void *)MP_QSTR_SEC_WPA2,
    (void *)MP_QSTR_SEC_WPA_WPA2,
    (void *)MP_QSTR_SEC_WPA2_ENT,
    (void *)MP_QSTR_SEC_WPA_ENT,
    (void *)MP_QSTR_SEC_WPA3,
    (void *)MP_QSTR_SEC_WPA2_WPA3,
    (void *)MP_QSTR_SEC_WAPI,
    (void *)MP_QSTR_SEC_OWE,
    (void *)MP_QSTR_SEC_DPP,
    (void *)MP_QSTR_SEC_WPA3_ENT,
    (void *)MP_QSTR_SEC_WPA2_WPA3_ENT,
    (void *)MP_QSTR_SEC_WPA3_ENT_192,
    (void *)MP_QSTR_SEC_WPA3_EXT_PSK,
    (void *)MP_QSTR_SEC_WPA3_EXT_PSK_MIXED_MODE,
    (void *)MP_QSTR_PM_NONE,
    (void *)MP_QSTR_PM_PERFORMANCE,
    (void *)MP_QSTR_PM_POWERSAVE,
    (void *)MP_QSTR_PROTOCOL_DEFAULT,
    (void *)MP_QSTR_PROTOCOL_LR,
    // network module globals injected by ports/esp32/modnetwork_globals.h
    // (deprecated WLAN constants kept on the module for back-compat). These are
    // referenced by the firmware build once MICROPY_PY_NETWORK_MODULE_GLOBALS_-
    // INCLUDEFILE is wired in mpconfigport.h, so the names must exist in the pool.
    (void *)MP_QSTR_PPP,
    (void *)MP_QSTR_MODE_11B,
    (void *)MP_QSTR_MODE_11G,
    (void *)MP_QSTR_MODE_11N,
    (void *)MP_QSTR_MODE_LR,
    (void *)MP_QSTR_AUTH_OPEN,
    (void *)MP_QSTR_AUTH_WEP,
    (void *)MP_QSTR_AUTH_WPA_PSK,
    (void *)MP_QSTR_AUTH_WPA2_PSK,
    (void *)MP_QSTR_AUTH_WPA_WPA2_PSK,
    (void *)MP_QSTR_AUTH_WPA2_ENTERPRISE,
    (void *)MP_QSTR_AUTH_WPA3_PSK,
    (void *)MP_QSTR_AUTH_WPA2_WPA3_PSK,
    (void *)MP_QSTR_AUTH_WAPI_PSK,
    (void *)MP_QSTR_AUTH_OWE,
    (void *)MP_QSTR_AUTH_WPA3_ENT_192,
    (void *)MP_QSTR_AUTH_WPA3_EXT_PSK,
    (void *)MP_QSTR_AUTH_WPA3_EXT_PSK_MIXED_MODE,
    (void *)MP_QSTR_AUTH_MAX,
    (void *)MP_QSTR_STAT_IDLE,
    (void *)MP_QSTR_STAT_CONNECTING,
    (void *)MP_QSTR_STAT_GOT_IP,
    (void *)MP_QSTR_STAT_NO_AP_FOUND,
    (void *)MP_QSTR_STAT_NO_AP_FOUND_IN_RSSI_THRESHOLD,
    (void *)MP_QSTR_STAT_NO_AP_FOUND_IN_AUTHMODE_THRESHOLD,
    (void *)MP_QSTR_STAT_NO_AP_FOUND_W_COMPATIBLE_SECURITY,
    (void *)MP_QSTR_STAT_WRONG_PASSWORD,
    (void *)MP_QSTR_STAT_BEACON_TIMEOUT,
    (void *)MP_QSTR_STAT_ASSOC_FAIL,
    (void *)MP_QSTR_STAT_CONNECT_FAIL,
    (void *)MP_QSTR_STAT_HANDSHAKE_TIMEOUT,
    // network.PPP (ports/esp32/network_ppp.c) — pulled into the network globals
    // because the Arduino IDF defines CONFIG_LWIP_PPP_SUPPORT, so network_ppp.c is
    // compiled + linked and these method/constant names must exist in the pool.
    (void *)MP_QSTR_stream,
    (void *)MP_QSTR_user,
    (void *)MP_QSTR_username,
    (void *)MP_QSTR_IRQ_RXIDLE,
    (void *)MP_QSTR_SEC_NONE,
    (void *)MP_QSTR_SEC_PAP,
    (void *)MP_QSTR_SEC_CHAP,
    (void *)MP_QSTR_AUTH_NONE,
    (void *)MP_QSTR_AUTH_PAP,
    (void *)MP_QSTR_AUTH_CHAP,
    // socket module (ports/esp32/modsocket.c)
    (void *)MP_QSTR_socket,
    (void *)MP_QSTR_getaddrinfo,
    (void *)MP_QSTR_AF_INET,
    (void *)MP_QSTR_AF_INET6,
    (void *)MP_QSTR_SOCK_STREAM,
    (void *)MP_QSTR_SOCK_DGRAM,
    (void *)MP_QSTR_SOCK_RAW,
    (void *)MP_QSTR_IPPROTO_TCP,
    (void *)MP_QSTR_IPPROTO_UDP,
    (void *)MP_QSTR_IPPROTO_IP,
    (void *)MP_QSTR_SOL_SOCKET,
    (void *)MP_QSTR_SO_REUSEADDR,
    (void *)MP_QSTR_IP_ADD_MEMBERSHIP,
    (void *)MP_QSTR_TCP_NODELAY,
    (void *)MP_QSTR_SO_BINDTODEVICE,
    (void *)MP_QSTR_bind,
    (void *)MP_QSTR_listen,
    (void *)MP_QSTR_accept,
    (void *)MP_QSTR_recv,
    (void *)MP_QSTR_recvfrom,
    (void *)MP_QSTR_sendto,
    (void *)MP_QSTR_setsockopt,
    (void *)MP_QSTR_settimeout,
    (void *)MP_QSTR_setblocking,
    (void *)MP_QSTR_makefile,
    (void *)MP_QSTR_fileno,
    (void *)MP_QSTR_SO_BROADCAST,
    (void *)MP_QSTR_MSG_PEEK,
    (void *)MP_QSTR_MSG_DONTWAIT,
    // ssl/tls module
    (void *)MP_QSTR_ssl,
    (void *)MP_QSTR_wrap_socket,
    (void *)MP_QSTR_SSLContext,
    (void *)MP_QSTR_PROTOCOL_TLS_CLIENT,
    (void *)MP_QSTR_PROTOCOL_TLS_SERVER,
    (void *)MP_QSTR_CERT_NONE,
    (void *)MP_QSTR_CERT_OPTIONAL,
    (void *)MP_QSTR_CERT_REQUIRED,
    (void *)MP_QSTR_server_hostname,
    (void *)MP_QSTR_server_side,
    (void *)MP_QSTR_do_handshake,
    (void *)MP_QSTR_cert_reqs,
    (void *)MP_QSTR_cadata,
    (void *)MP_QSTR_cafile,
    (void *)MP_QSTR_certfile,
    (void *)MP_QSTR_keyfile,
    (void *)MP_QSTR_load_cert_chain,
    (void *)MP_QSTR_load_verify_locations,
    (void *)MP_QSTR_verify_mode,
    (void *)MP_QSTR_getpeercert,
    (void *)MP_QSTR_cipher,
    (void *)MP_QSTR_verify_callback,
    (void *)MP_QSTR_do_handshake_on_connect,
    (void *)MP_QSTR_client_id,
    (void *)MP_QSTR_get_ciphers,
    (void *)MP_QSTR_set_ciphers,
    (void *)MP_QSTR_recv_into,
    (void *)MP_QSTR_sendall,
    (void *)MP_QSTR_SSLSocket,
    (void *)MP_QSTR_tls,
    (void *)MP_QSTR_MBEDTLS_VERSION,
    (void *)MP_QSTR_PROTOCOL_DTLS_CLIENT,
    (void *)MP_QSTR_PROTOCOL_DTLS_SERVER,
    // webrepl / websocket
    (void *)MP_QSTR_webrepl,
    (void *)MP_QSTR_websocket,
    (void *)MP_QSTR_start,
    (void *)MP_QSTR__webrepl,
    (void *)MP_QSTR_wb,
    // bluetooth (extmod/modbluetooth.c)
    (void *)MP_QSTR_bluetooth,
    (void *)MP_QSTR_BLE,
    (void *)MP_QSTR_gap_advertise,
    (void *)MP_QSTR_gap_scan,
    (void *)MP_QSTR_gap_connect,
    (void *)MP_QSTR_gap_disconnect,
    (void *)MP_QSTR_gap_name,
    (void *)MP_QSTR_gap_pair,
    (void *)MP_QSTR_gap_passkey,
    (void *)MP_QSTR_gatts_register_services,
    (void *)MP_QSTR_gatts_read,
    (void *)MP_QSTR_gatts_write,
    (void *)MP_QSTR_gatts_notify,
    (void *)MP_QSTR_gatts_indicate,
    (void *)MP_QSTR_gatts_set_buffer,
    (void *)MP_QSTR_gattc_discover_services,
    (void *)MP_QSTR_gattc_discover_characteristics,
    (void *)MP_QSTR_gattc_discover_descriptors,
    (void *)MP_QSTR_gattc_read,
    (void *)MP_QSTR_gattc_write,
    (void *)MP_QSTR_gattc_exchange_mtu,
    (void *)MP_QSTR_hci_cmd,
    (void *)MP_QSTR_l2cap_listen,
    (void *)MP_QSTR_l2cap_connect,
    (void *)MP_QSTR_l2cap_disconnect,
    (void *)MP_QSTR_l2cap_send,
    (void *)MP_QSTR_l2cap_recvinto,
    (void *)MP_QSTR_FLAG_READ,
    (void *)MP_QSTR_FLAG_WRITE,
    (void *)MP_QSTR_FLAG_NOTIFY,
    (void *)MP_QSTR_FLAG_INDICATE,
    (void *)MP_QSTR_FLAG_WRITE_NO_RESPONSE,
    (void *)MP_QSTR_UUID,
    (void *)MP_QSTR_interval_us,
    (void *)MP_QSTR_window_us,
    (void *)MP_QSTR_duration_ms,
    (void *)MP_QSTR_conn_handle,
    (void *)MP_QSTR_adv_data,
    (void *)MP_QSTR_resp_data,
    (void *)MP_QSTR_connectable,
    (void *)MP_QSTR_addr_mode,
    (void *)MP_QSTR_bond,
    (void *)MP_QSTR_mitm,
    (void *)MP_QSTR_le_secure,
    (void *)MP_QSTR_io,
    (void *)MP_QSTR_mtu,
    // temporalbadge: REPL screenshot hotkey symbol (single-letter qstrs are
    // sometimes missed by the makeqstrdata.py scanner — declare explicitly).
    (void *)MP_QSTR_o,
};

// Module-table registrations for the network family. The real markers live in
// ports/esp32/modsocket.c, extmod/modnetwork.c, ports/esp32/modespnow.c, and
// extmod/modtls_mbedtls.c, but they sit inside `#if MICROPY_PY_NETWORK` /
// `#if MICROPY_PY_ESPNOW` / `#if MICROPY_PY_SSL` and pull in lwip / esp_wifi /
// mbedtls headers that host `gcc -E` can't resolve (so modtls_mbedtls.c is not
// in SRC_QSTR and the network gates are forced off for this host pass). Re-emit
// the markers here so makemoduledefs.py records them; the firmware build skips
// this whole #else branch and links the real mp_module_* symbols, so `import
// socket` / `network` / `_espnow` / `tls` resolve. `ssl`/`espnow` are pure-Python
// facades on /lib that wrap `tls`/`_espnow`. Keep in sync with those sources.
MP_REGISTER_EXTENSIBLE_MODULE(MP_QSTR_socket, mp_module_socket);
MP_REGISTER_MODULE(MP_QSTR_network, mp_module_network);
MP_REGISTER_MODULE(MP_QSTR__espnow, mp_module_espnow);
MP_REGISTER_MODULE(MP_QSTR_tls, mp_module_tls);
#endif
