import time
print("=== 5. Haptics & Tone ===")
oled_clear(True)
oled_set_cursor(0, 0)
oled_println("5. Haptics")

s = haptic_strength()
print("  strength=" + str(s))
oled_println("str:" + str(s))

print("  default pulse")
oled_println("default pulse")
haptic_pulse()
time.sleep_ms(400)

print("  strong pulse")
oled_println("strong pulse")
haptic_pulse(255, 80)
time.sleep_ms(400)

print("  gentle pulse")
oled_println("gentle pulse")
haptic_pulse(60, 20)
time.sleep_ms(400)

haptic_strength(180)
rb = haptic_strength()
print("  set 180 read=" + str(rb))
haptic_strength(s)

oled_clear(True)
oled_set_cursor(0, 0)
oled_println("5. Coil Tone")
oled_println("C major scale")
print("  scale")
tone(262, 150)
time.sleep_ms(200)
tone(330, 150)
time.sleep_ms(200)
tone(392, 150)
time.sleep_ms(200)
tone(523, 150)
time.sleep_ms(200)

oled_println("440Hz hold")
print("  440Hz continuous")
tone(440)
time.sleep_ms(600)
p = tone_playing()
print("  playing=" + str(p))
no_tone()
print("  no_tone, playing=" + str(tone_playing()))
oled_println("stopped")
time.sleep_ms(400)
